#!/bin/bash

set -euo pipefail

REPO_DIR=$(pwd -P)
REPO_NAME=$(basename "$REPO_DIR")

function clone_repo {
  local ref_name=$1
  local work_dir
  work_dir="/home/git/work/$REPO_NAME/$ref_name/$(date +%F)/$(date +%H_%M_%S)"

  git clone "$REPO_DIR" "$work_dir"
  GIT_WORK_TREE=$work_dir GIT_DIR="${work_dir}/.git" git checkout main
}

# shellcheck disable=SC2034
while read -r oldrev newrev refname; do
  case "$refname" in
      refs/heads/*)
        if [ "$newrev" = "0000000000000000000000000000000000000000" ]; then
            echo "Skipping deleted branch"
            continue
        fi
        clone_repo "$refname"
        ;;
      refs/tags/*)
        echo "Skipping non-commit tag ref \$refname"
        ;;
      *)
        echo "Skipping unknown ref type \$refname"
        ;;
    esac
done
